# Generated by Django 5.0.7 on 2024-07-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Path Name"
            ),
        ),
    ]
