# Generated by Django 5.0.7 on 2024-07-29 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Topic Title"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="week",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(52),
                ],
                verbose_name="Week",
            ),
        ),
    ]
